version: '3.2'
services:
  # Apache
  www:
    container_name: yii_server
    build:
      context: ./server
    ports:
      - 80:80
      - 443:443
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - ./:/var/www

  # MySQL
  db:
    container_name: yii_database
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    volumes:
      - ./runtime/database:/var/lib/mysql