version: '3.7'
services:
  php:
    image: manchenkoff/apache-php-xdebug
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/app/:cached
    environment:
      PHP_IDE_CONFIG: serverName=localhost

  db:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    volumes:
      - ./runtime/database:/var/lib/mysql